language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ADDITIONAL_DEBS='apt-utils dialog'
    - CATKIN_LINT=pedantic
    - CMAKE_ARGS=-DCMAKE_BUILD_TYPE=Release
    - PARALLEL_TESTS=1
    - PYLINT_ARGS='--output-format=parseable --errors-only --disable=method-hidden'
    - PYLINT_CHECK=true
    - ROS_REPO=main
  matrix:
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=noetic
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
